---

- name: Make sure account exists and has given contacts. We agree to TOS.
  acme_account:
    account_key_src: private/letsencrypt_account.key
    acme_directory: https://acme-v02.api.letsencrypt.org/directory
    acme_version: 2
    state: present
    terms_agreed: yes
    contact:
    - mailto:support@ebookfoundation.org
  delegate_to: 127.0.0.1

- name: Create a challenge for server_name using a account key file.
  acme_certificate:
    account_key_src: private/letsencrypt_account.key
    acme_directory: https://acme-v02.api.letsencrypt.org/directory
    acme_version: 2
    select_crypto_backend: openssl
    csr: "private/{{ server_name }}.csr"
    dest: tmp/server.crt
    fullchain_dest: /tmp/server.ca-bundle
  delegate_to: 127.0.0.1
  register: acme_challenge


- name: Create .well-known directory
  become: yes
  file: 
    path: "/var/www/static/.well-known"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0755

- name: Create acme-challenge directory
  become: yes
  file: 
    path: "/var/www/static/.well-known/acme-challenge"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0755

- copy:
    dest: /var/www/static/{{ acme_challenge['challenge_data'][server_name]['http-01']['resource'] }}
    content: "{{ acme_challenge['challenge_data'][server_name]['http-01']['resource_value'] }}"
  when: acme_challenge is changed

- name: Create a challenge for server_name using a account key file.
  acme_certificate:
    account_key_src: private/letsencrypt_account.key
    acme_directory: https://acme-v02.api.letsencrypt.org/directory
    acme_version: 2
    select_crypto_backend: openssl
    csr: "private/{{ server_name }}.csr"
    dest: /tmp/server.crt
    fullchain_dest: /tmp/server.ca-bundle
    data: "{{ acme_challenge }}"
  delegate_to: 127.0.0.1
    
- name: Copy certs
  become: yes
  copy: 
    src: /tmp/{{ item }}
    dest: /etc/ssl/certs/{{ item }}.key
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0600
  with_items:
    - 'server.crt'
    - 'server.ca-bundle'
  notify: 
    - restart apache
  tags:
    - certs

- name: Copy server key
  become: yes
  copy: 
    src: private/{{ server_name }}.key
    dest: /etc/ssl/private/server.key
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0600
  notify: 
    - restart apache
  tags:
    - certs
