---

- name: Make sure account exists and has given contacts. We agree to TOS.
  acme_account:
    account_key_src: certs/account-key.pem
    state: present
    terms_agreed: yes
    contact:
    - mailto: support@ebookfoundation.org

- name: Create a challenge for server_name using a account key file.
  acme_certificate:
    account_key_src: certs/account-key.pem
    csr: "certs/{{ server_name }}.csr"
    dest: /etc/ssl/certs/server.crt
    fullchain_dest: /etc/ssl/certs/server-fullchain.crt
  register: acme_challenge

- copy:
    dest: /var/www/static/lencrypt/{{ acme_challenge['challenge_data'][server_name]['http-01']['resource'] }}
    content: "{{ acme_challenge['challenge_data'][server_name]['http-01']['resource_value'] }}"
    when: acme_challenge is changed

- name: Create a challenge for server_name using a account key file.
  acme_certificate:
    account_key_src: certs/account-key.pem
    csr: "certs/{{ server_name }}.csr"
    dest: /etc/ssl/certs/server.crt
    fullchain_dest: /etc/ssl/certs/server-fullchain.crt"
    data: "{{ acme_challenge }}"
    
- name: Copy server key
  become: yes
  copy: 
    src: certs/m.unglue.it.key
    dest: /etc/ssl/private/server.key
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0600
  notify: 
    - restart apache
  tags:
    - certs

